package com.justindriggers.vulkan.devices.physical.models;

import com.justindriggers.vulkan.models.Maskable;
import org.lwjgl.vulkan.EXTSamplerFilterMinmax;
import org.lwjgl.vulkan.IMGFilterCubic;
import org.lwjgl.vulkan.VK10;
import org.lwjgl.vulkan.VK11;

public enum FormatFeature implements Maskable {

    SAMPLED_IMAGE(VK10.VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT),
    STORAGE_IMAGE(VK10.VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT),
    STORAGE_IMAGE_ATOMIC(VK10.VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT),
    COLOR_ATTACHMENT(VK10.VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT),
    COLOR_ATTACHMENT_BLEND(VK10.VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT),
    DEPTH_STENCIL_ATTACHMENT(VK10.VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT),
    BLIT_SRC(VK10.VK_FORMAT_FEATURE_BLIT_SRC_BIT),
    BLIT_DST(VK10.VK_FORMAT_FEATURE_BLIT_DST_BIT),
    SAMPLED_IMAGE_FILTER_LINEAR(VK10.VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT),
    TRANSFER_SRC(VK11.VK_FORMAT_FEATURE_TRANSFER_SRC_BIT),
    TRANSFER_DST(VK11.VK_FORMAT_FEATURE_TRANSFER_DST_BIT),
    SAMPLED_IMAGE_FILTER_MINMAX_EXT(EXTSamplerFilterMinmax.VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_MINMAX_BIT_EXT),
    SAMPLED_IMAGE_FILTER_CUBIC_IMG(IMGFilterCubic.VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_IMG),
    MIDPOINT_CHROMA_SAMPLES(VK11.VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT),
    COSITED_CHROMA_SAMPLES(VK11.VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT),
    SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER(VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT),
    SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER(VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT),
    SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT(VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT),
    SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE(VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT),
    DISJOINT(VK11.VK_FORMAT_FEATURE_DISJOINT_BIT);
    
    private final int bit;
    
    FormatFeature(final int bit) {
        this.bit = bit;
    }

    @Override
    public int getBitValue() {
        return bit;
    }
}
