package com.justindriggers.vulkan.pipeline.models.assembly;

import com.justindriggers.vulkan.models.HasValue;
import org.lwjgl.vulkan.VK10;

public enum PrimitiveTopology implements HasValue<Integer> {

    POINT_LIST(VK10.VK_PRIMITIVE_TOPOLOGY_POINT_LIST),
    LINE_LIST(VK10.VK_PRIMITIVE_TOPOLOGY_LINE_LIST),
    LINE_STRIP(VK10.VK_PRIMITIVE_TOPOLOGY_LINE_STRIP),
    TRIANGLE_LIST(VK10.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST),
    TRIANGLE_STRIP(VK10.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP),
    TRIANGLE_FAN(VK10.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN),
    LINE_LIST_WITH_ADJACENCY(VK10.VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY),
    LINE_STRIP_WITH_ADJACENCY(VK10.VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY),
    TRIANGLE_LIST_WITH_ADJACENCY(VK10.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY),
    TRIANGLE_STRIP_WITH_ADJACENCY(VK10.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY),
    PATCH_LIST(VK10.VK_PRIMITIVE_TOPOLOGY_PATCH_LIST);

    private final int value;

    PrimitiveTopology(final int value) {
        this.value = value;
    }

    @Override
    public Integer getValue() {
        return value;
    }
}
