package com.justindriggers.vulkan.pipeline.models;

import com.justindriggers.vulkan.models.Maskable;
import org.lwjgl.vulkan.VK10;

public enum PipelineStage implements Maskable {

    TOP_OF_PIPE(VK10.VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT),
    DRAW_INDIRECT(VK10.VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT),
    VERTEX_INPUT(VK10.VK_PIPELINE_STAGE_VERTEX_INPUT_BIT),
    VERTEX_SHADER(VK10.VK_PIPELINE_STAGE_VERTEX_SHADER_BIT),
    TESSELATION_CONTROL_SHADER(VK10.VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT),
    TESSELATION_EVALUATION_SHADER(VK10.VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT),
    GEOMETRY_SHADER(VK10.VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT),
    FRAGMENT_SHADER(VK10.VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT),
    EARLY_FRAGMENT_TESTS(VK10.VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT),
    LATE_FRAGEMENT_TESTS(VK10.VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT),
    COLOR_ATTACHMENT_OUTPUT(VK10.VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT),
    COMPUTE_SHADER(VK10.VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT),
    TRANSFER(VK10.VK_PIPELINE_STAGE_TRANSFER_BIT),
    BOTTOM_OF_PIPE(VK10.VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT),
    HOST(VK10.VK_PIPELINE_STAGE_HOST_BIT),
    ALL_GRAPHICS(VK10.VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT),
    ALL_COMMANDS(VK10.VK_PIPELINE_STAGE_ALL_COMMANDS_BIT);

    private final int bit;

    PipelineStage(final int bit) {
        this.bit = bit;
    }

    @Override
    public int getBitValue() {
        return bit;
    }
}
